D&a note
djpr-data/djprtradedash pull request #113
Opened 2022-05-02 07:35 UTC by Emma-DJPR

1. note.md created
2. The document was inserted into page methodology.R 
 Build and check showed one warning and 4 notes. Please check

2022-05-10 01:36 UTC, mrjoh3 requested changes
need to change the last 3 sentences in the second paragraph. Please see the note in the PR

2022-05-10 01:36 UTC, mrjoh3 commented on R/note.md
> +**SPP's Data and Analytics** Unit works with diverse clients across DJPR to analyse data, build data products and facilitate data reporting, such as interactive dashboards, and improve data capabilit
the link in here is for the DJPR intranet, but the app will be public. Please replace the last 3 sentences with :

```
Please [email us](mailto:spp-data@ecodev.vic.gov.au?subject=DJPR%20Trade%20Dashboard) with any comments or feedback.
```

2022-05-10 03:38 UTC, mrjoh3 approved these changes

2022-05-10 03:41 UTC, mrjoh3 commented
@Emma-DJPR can you also the file to the methodology page. Once this is done I will merge

2022-08-16 04:44 UTC, Henry-DJPR commented
edits superseded

2022-08-16 04:44 UTC, closed without merging